- name: default
  destination: 0.0.0.0/0
  next_hop: 10.2.1.1
- name: on-prem
  destination: 192.168.0.0/16
  next_hop: 192.168.0.1
- name: azure
  destination: 172.16.0.0/16
  next_hop: 172.16.0.1
- name: bad-route
  destination: 172.17.0.0/16
  next_hop: 172.17.0.1
