on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Open Policy Agent
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Evaluate OPA Policy
      id: opa_eval
      uses: migara/test-action@master
      with:
        tests: /tests/panos.rego
        policy: /policy.yml
    - name: Print Results
      # run: echo "Output ${{ steps.opa_eval.outputs.opa_results }}"
      # run: |
      #   echo $opa_results | jq -r '.result[].expressions[].value'
      # env:
      #   opa_results: ${{ steps.opa_eval.outputs.opa_results}}